name: fv3dataset-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cftime
  - dask
  - h5netcdf
  - pip
  - pytest
  - xarray
  - pip:
    - coveralls
    - git+https://github.com/ai2cm/fv3net.git@c385103607eea718905846807295621e8ebc5033#egg=synth&subdirectory=external/synth
    - pytest-cov